Repository 202ecommerce/paypal, pull requests merged in 2023-08, with the labels that each got.

#252 refs #40939 small modification
  views/templates/admin/_partials/forms/pp_account_form.tpl
Labels: enhancement

#253 refs #41063 error in console
  .htaccess
Labels: enhancement

#254 refs #41631 - Improve errors message
  202/_dev/js/admin/form.js
  controllers/admin/AdminPaypalConfigurationController.php
  translations/es.php
  translations/fr.php
  translations/it.php
  views/templates/admin/_partials/alert_ajax.tpl
Labels: enhancement, php, javascript

#260 Hotfixes/41672 parse transaction date
  classes/API/Request/PaypalCaptureAuthorizeRequest.php
  classes/API/Request/PaypalOrderAuthorizeRequest.php
  classes/API/Request/PaypalOrderCaptureRequest.php
  classes/API/Request/PaypalOrderGetRequest.php
  classes/API/Request/PaypalOrderRefundRequest.php
  classes/API/Request/V_1/PaypalOrderCaptureRequest.php
  classes/API/Request/V_1/PaypalOrderRefundRequest.php
Labels: bug

#256 refs #41589 - Fix webhook order message
  202/build.xml
  services/WebhookService.php
Labels: bug, php

#259 refs #41724 compatibility with PS 1.7.2.x
  views/templates/admin/_partials/forms/pp_account_form.tpl
Labels: bug

#262 refs #41589 small fix
  services/WebhookService.php
  upgrade/Upgrade-6.0.3.php
Labels: bug
